In [2]:
import numpy as np
import time

In [5]:
#execution performance

size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end-start} sec")

#numpy arrays
np_arr=np.array(py_list)
start=time.time()
sq_array=np_arr**2
end = time.time()
print(f"Numpy array list time = {end-start} sec")

Python list time = 0.048664093017578125 sec
Numpy array list time = 0.001194000244140625 sec


In [13]:
#create array
arr1=np.zeros((2,3), dtype="int64") #with null values
print("Zero array :",arr1,arr1.shape)

arr2=np.ones((5,), dtype="int64") #prefill
print("prefill array :",arr2,arr2.shape)

arr3=np.full((4,3), 100)#prefill with value
print("Zero array :",arr3,arr3.shape)

arr4=np.eye(3) #identity matrix
print(arr4,arr4.shape)

arr5=np.arange(0,11,2)#range elements
print(arr5,arr5.shape)

arr6=np.linspace(1,100,4)#evenly spaced arrays
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] (4, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)
